services:
  - type: web
    name: generador-actas
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10

  # Un Servicio de Base de Datos para MySQL
  - type: pserv
    name: actas # Elige un nombre para tu base de datos
    env: mysql
    plan: free # El plan gratuito para bases de datos
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 1
    envVars:
      - key: MYSQL_DATABASE
        value: actas # El nombre de tu base de datos
      - key: MYSQL_USER
        value: sam_user # Elige un nombre de usuario
      - key: MYSQL_PASSWORD
        generateValue: true # Render generar치 una contrase침a segura
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true # Render generar치 una contrase침a segura para root
